# Generated by Django 5.2 on 2025-04-20 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('material', '0001_initial'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('mat_cod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material', to='material.material')),
                ('ser_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servico', to='servicos.servico')),
            ],
        ),
    ]
