# Generated by Django 5.2 on 2025-04-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('mat_cod', models.AutoField(primary_key=True, serialize=False)),
                ('mat_desc', models.CharField(max_length=255)),
                ('mat_etq', models.IntegerField(blank=True, null=True)),
                ('mat_preco_unit', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('mat_fne', models.CharField(blank=True, max_length=200, null=True)),
                ('mat_dt_aqui', models.DateField(blank=True, null=True)),
                ('mat_obs', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
