# Generated by Django 5.2 on 2025-04-25 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
        ('modelo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='mat_modelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modelo_material', to='modelo.modelo'),
        ),
    ]
