# Generated by Django 5.2 on 2025-04-25 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servico',
            old_name='ser_desc',
            new_name='ser_obs',
        ),
        migrations.AddField(
            model_name='servico',
            name='ser_titulo',
            field=models.CharField(blank=True, null=True),
        ),
    ]
