# Generated by Django 5.2 on 2025-04-25 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('mod_id', models.AutoField(primary_key=True, serialize=False)),
                ('mod_nome', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
