# Generated by Django 5.2 on 2025-04-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('func_id', models.AutoField(primary_key=True, serialize=False)),
                ('func_nome', models.CharField(max_length=255)),
                ('func_cpf', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('func_rg', models.CharField(blank=True, max_length=20, null=True)),
                ('func_tel', models.CharField(blank=True, max_length=20, null=True)),
                ('func_cel', models.CharField(blank=True, max_length=20, null=True)),
                ('func_email', models.CharField(blank=True, max_length=100, null=True)),
                ('func_cargo', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
